// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Society struct {
	ID          int32
	Name        string
	PresidentID pgtype.Int4
	Active      pgtype.Bool
}

type SocietyCoordinator struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
}

type Student struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
}

type StudentSociety struct {
	StudentID int32
	SocietyID int32
}
