version: "3.8"

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: postgres_ubu
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      # - psql_volume:/var/lib/postgresql/data
#
# volumes:
#   psql_volume:
